### ISSUE TITLE
normalizedAffineGapDistance returns wrong value when parameters are Japanese(UTF-8 string)

### ISSUE THREAD

**Issue by JunNakamura** [dedupeio/affinegap#7]
I try to normalized affine gap for japanese strings such a "日本"

I make a script to test.
Then affinegap.normalizedAffineGapDistance("日本", "日本") returns 0.166666671634 which is wrong, should be 0.5.

```
import affinegap
import sys

args = sys.argv
word1 = args[1]
word2 = args[2]

#print word1
#print word2

normalizer = len(word1.decode("utf8")) + len(word2.decode("utf8"))

print "normalizer by utf8 decode"
print normalizer

print "normalizer of byte length"
print len(word1) + len(word2)


d = affinegap.affineGapDistance(word1, word2)
print "affine gap"
print d


print "expected normalized value"
print d/normalizer

nd = affinegap.normalizedAffineGapDistance(word1, word2)
print "normalized value"
print nd
```

```
# python affine_gap_test.py "日本" "日本"
normalizer by utf8 decode
4
affine gap
2.0
expected normalized value
0.5
normalized value
0.166666671634
```

I think, it causes a definition of normalizer.  

https://github.com/dedupeio/affinegap/blob/master/affinegap/affinegap.pyx#L122 and L123 shoud be change to 

```
cdef int length1 = len(_ustring(string1))
 cdef int length2 = len(_ustring(string2))
```

Or, affineGapDistance use byte length of input parameter instead of unicode length.

**Comment by fgregg** [comment]
thanks for the report. it only affects python 2.7 which we no longer support.
